version: "3.2"
services: 
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  collector:
    container_name: tweet-collector
    image: node:14
    working_dir: /usr/src/tweet-collector
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    env_file:
      - ./.env
    volumes: 
      - ./dist/:/usr/src/tweet-collector/dist/:z
      - ./package.json:/usr/src/tweet-collector/package.json:z   
    links: 
      - rabbitmq