version: "3.2"
services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db:z
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3.8
    restart: always
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  tweet-collector:
    container_name: tweet-collector
    image: node:14
    working_dir: /usr/src/tweet-collector
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    environment: 
      - MONGO_URL=mongodb://mongo:27017/TCC
    env_file:
      - ./.env
    volumes: 
      - ./dist/:/usr/src/tweet-collector/dist/:z
      - ./package.json:/usr/src/tweet-collector/package.json:z   
    links: 
      - rabbitmq
      - mongo