version: "3.2"
services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always
    volumes:
      - ./data:/data/db:z
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.8-management
    restart: always
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq  

  tweet-collector:
    container_name: tweet-collector
    image: node:14
    working_dir: /usr/src/tweet-collector
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    environment: 
      - MONGO_URL=mongodb://mongo:27017/TCC      
    env_file:
      - ./.env
    volumes: 
      - ./dist/:/usr/src/tweet-collector/dist/:z
      - ./package.json:/usr/src/tweet-collector/package.json:z
    links: 
      - rabbitmq
      - mongo  

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    # networks:
    #   - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    # networks:
    #   - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    # networks:
    #   - elk
    depends_on:
      - elasticsearch
      
# networks:
#   elk:
#     driver: bridge
#   rabbitmq:
#     driver: bridge